"use client";

import Link from "next/link";
import { useEffect, useState, type ReactNode } from "react";
import { ArrowRight, Bell, Check, ChevronDown, CircleHelp, Copy, Gift, Image as ImageIcon, KeyRound, LayoutDashboard, Menu, PackageCheck, Plus, ReceiptText, Search, Settings, ShieldCheck, TicketCheck, Trash2, Upload, UsersRound, WalletCards, X } from "lucide-react";
import { BrandLogo } from "./brand";

export type AccountTab = "overview"|"recharge"|"usage"|"keys"|"orders"|"assets"|"team"|"invite"|"tickets"|"settings";
const accountNav: {key:AccountTab;label:string;icon:typeof LayoutDashboard}[]=[
  {key:"overview",label:"账户概览",icon:LayoutDashboard},{key:"recharge",label:"余额充值",icon:WalletCards},{key:"usage",label:"用量与账单",icon:ReceiptText},{key:"keys",label:"API 密钥",icon:KeyRound},{key:"orders",label:"订单记录",icon:PackageCheck},{key:"assets",label:"资产管理",icon:ImageIcon},{key:"team",label:"团队成员",icon:UsersRound},{key:"invite",label:"邀请返佣",icon:Gift},{key:"tickets",label:"工单客服",icon:TicketCheck},{key:"settings",label:"账号设置",icon:Settings},
];
const baseOrderRows=[["ORD-260930-001","余额充值","¥100.00","微信支付","已完成","2026-09-30 10:21"],["ORD-260918-008","专业版月卡","¥59.00","支付宝","已完成","2026-09-18 14:08"],["ORD-260812-002","团队扩容","¥199.00","余额支付","已完成","2026-08-12 09:32"]];

export default function AccountCenter({initialTab="overview"}:{initialTab?:AccountTab}){
  const [tab,setTab]=useState<AccountTab>(initialTab);
  const [mobile,setMobile]=useState(false);
  const [toast,setToast]=useState("");
  const [keyCreated,setKeyCreated]=useState(false);
  const [balanceCents,setBalanceCents]=useState(12860);
  useEffect(()=>{void fetch("/api/inspirations",{cache:"no-store"}).then(async response=>await response.json() as {balanceCents:number}).then(payload=>setBalanceCents(payload.balanceCents)).catch(()=>{/* keep the last known balance */})},[]);
  function notify(message:string){setToast(message);window.setTimeout(()=>setToast(""),2200)}
  return <main className="account-shell">{toast&&<div className="platform-toast"><Check/>{toast}</div>}<aside className={mobile?"open":""}><header><Link href="/"><BrandLogo/></Link><button onClick={()=>setMobile(false)}><X/></button></header><nav>{accountNav.map(item=><button key={item.key} className={tab===item.key?"active":""} onClick={()=>{setTab(item.key);setMobile(false)}}><item.icon/>{item.label}{item.key==="tickets"&&<small>2</small>}</button>)}</nav><footer><Link href="/home"><ArrowRight/>返回创作工作台</Link><Link href="/admin"><ShieldCheck/>运营管理后台</Link></footer></aside><section><header className="account-topbar"><div><button onClick={()=>setMobile(true)}><Menu/></button><span><h1>{accountNav.find(item=>item.key===tab)?.label}</h1><small>管理账户、用量与团队服务</small></span></div><div><button><CircleHelp/>帮助中心</button><button className="bell"><Bell/><i>2</i></button><button className="account-user"><i>灵</i><span><b>演示用户</b><small>专业版</small></span><ChevronDown/></button></div></header><div className="account-content">
    {tab==="overview"&&<Overview go={setTab} balanceCents={balanceCents}/>}
    {tab==="recharge"&&<Recharge notify={notify} balanceCents={balanceCents}/>}
    {tab==="usage"&&<Usage/>}
    {tab==="keys"&&<ApiKeys created={keyCreated} create={()=>{setKeyCreated(true);notify("演示密钥已创建")}} notify={notify}/>}
    {tab==="orders"&&<Orders/>}
    {tab==="assets"&&<Assets notify={notify}/>}
    {tab==="team"&&<Team notify={notify}/>}
    {tab==="invite"&&<Invite notify={notify}/>}
    {tab==="tickets"&&<Tickets notify={notify}/>}
    {tab==="settings"&&<AccountSettings notify={notify}/>}
  </div></section></main>
}

function Overview({go,balanceCents}:{go:(tab:AccountTab)=>void;balanceCents:number}){return <><div className="account-welcome"><div><span>上午好，演示用户</span><h2>今天想用 AI 完成什么？</h2><p>你的账户与服务运行正常，所有模型均可使用。</p><Link className="continue-button" href="/home">继续创作 <ArrowRight/></Link></div><div><i>PRO</i><span>专业版会员<small>有效期至 2026-12-31</small></span><b>剩余 92 天</b></div></div><div className="account-stat-grid"><article><span>可用余额</span><b>¥{(balanceCents/100).toFixed(2)}</b><small>与灵感商城实时同步</small><button onClick={()=>go("recharge")}>充值</button></article><article><span>本月消费</span><b>¥286.42</b><small>较上月下降 12.4%</small></article><article><span>本月调用</span><b>1,286</b><small>对话 936 · 媒体 350</small></article><article><span>团队成员</span><b>8 / 15</b><small>本月团队消费 ¥1,286</small><button onClick={()=>go("team")}>管理</button></article></div><div className="overview-grid"><article className="usage-chart"><header><span><b>近 7 天消费趋势</b><small>模型与 API 消费合计</small></span><button>最近 7 天 <ChevronDown/></button></header><div className="mini-bars">{[38,62,45,78,53,91,70].map((height,index)=><span key={index}><i style={{height:`${height}%`}}/><small>{["一","二","三","四","五","六","日"][index]}</small></span>)}</div></article><article className="quick-entry"><header><b>快捷入口</b></header><div><button onClick={()=>go("keys")}><KeyRound/><span><b>API 密钥</b><small>创建与管理调用密钥</small></span><ArrowRight/></button><button onClick={()=>go("usage")}><ReceiptText/><span><b>用量账单</b><small>查看模型消费明细</small></span><ArrowRight/></button><button onClick={()=>go("invite")}><Gift/><span><b>邀请返佣</b><small>邀请好友获得奖励</small></span><ArrowRight/></button><button onClick={()=>go("tickets")}><TicketCheck/><span><b>提交工单</b><small>获取人工技术支持</small></span><ArrowRight/></button></div></article></div></>}

function Recharge({notify,balanceCents}:{notify:(message:string)=>void;balanceCents:number}){const [amount,setAmount]=useState(100);return <div className="recharge-page"><section><header><WalletCards/><span><b>账户余额</b><small>余额适用于主站创作、灵感模板和 API 调用</small></span><strong>¥{(balanceCents/100).toFixed(2)}</strong></header><h3>选择充值金额</h3><div className="recharge-amounts">{[20,50,100,200,500,1000].map(value=><button key={value} className={amount===value?"active":""} onClick={()=>setAmount(value)}><b>¥{value}</b>{value>=500&&<small>赠送 ¥{value/25}</small>}</button>)}</div><label>自定义金额<input type="number" value={amount} onChange={event=>setAmount(Number(event.target.value))}/></label><h3>支付方式</h3><div className="pay-methods"><button className="active">微信支付</button><button>支付宝</button><button>兑换码</button></div><button className="pay-now" onClick={()=>notify("演示环境未绑定支付商户")}>确认支付 ¥{amount.toFixed(2)}</button></section><aside><h3>充值说明</h3><p>充值成功后余额实时到账，可用于网页创作、购买灵感模板与 API 调用。</p><p>赠送余额不可提现，退款按实际支付金额处理。</p><p>企业大额充值可联系在线客服开具发票。</p></aside></div>}

function Usage(){return <><div className="usage-summary"><article><span>本月总消费</span><b>¥286.42</b><small>9 月 1 日—9 月 30 日</small></article><article><span>对话模型</span><b>¥126.80</b><small>936 次调用</small></article><article><span>媒体模型</span><b>¥159.62</b><small>350 个生成任务</small></article></div><DataSection title="消费明细" description="按模型和任务查询每一笔额度变化" columns={["流水号","业务","模型","用量","金额","余额","时间"]} rows={[["BL-938201","对话","GPT-5","2,830 tokens","¥0.056","¥128.60","今天 10:32"],["BL-938188","图片","GPT Image 1","1 张","¥0.120","¥128.66","今天 10:18"],["BL-938102","视频","Seedance 2","10 秒","¥1.800","¥128.78","今天 09:41"],["BL-937980","API","Claude Sonnet 4.5","8,120 tokens","¥0.162","¥130.58","昨天 22:16"]]}/></>}

function Orders(){
  const [rows,setRows]=useState(baseOrderRows);
  useEffect(()=>{void fetch("/api/inspirations/orders",{cache:"no-store"}).then(async response=>await response.json() as {orders:{orderNo:string;title:string;amountCents:number;status:string;createdAt:string}[]}).then(payload=>{
    const marketplaceRows=payload.orders.map(order=>[order.orderNo,`同款模板 · ${order.title}`,`¥${(order.amountCents/100).toFixed(2)}`,order.amountCents===0?"免费领取":"余额支付",order.status==="paid"?"已完成":order.status,new Date(`${order.createdAt}Z`).toLocaleString("zh-CN",{hour12:false})]);
    setRows([...marketplaceRows,...baseOrderRows]);
  }).catch(()=>{/* keep the sample account history */})},[]);
  return <DataSection title="订单记录" description="查看套餐、充值和灵感同款模板订单" columns={["订单号","订单类型","金额","支付方式","状态","创建时间"]} rows={rows}/>;
}

function ApiKeys({created,create,notify}:{created:boolean;create:()=>void;notify:(message:string)=>void}){const rows=created?[["开发测试密钥","sk-lz-demo••••••9H2K","不限","¥0.00","正常","刚刚"],["生产环境","sk-lz-prod••••••K82M","¥500/月","¥126.80","正常","今天 09:10"]]:[["生产环境","sk-lz-prod••••••K82M","¥500/月","¥126.80","正常","今天 09:10"]];return <><div className="api-key-banner"><div><KeyRound/><span><b>统一 API 地址</b><code>https://api.your-domain.com/v1</code></span></div><button onClick={()=>notify("地址已复制")}><Copy/>复制地址</button></div><section className="data-section"><header><span><h2>API 密钥</h2><p>为不同应用创建独立密钥和额度限制</p></span><button onClick={create}><Plus/>创建密钥</button></header><AccountTable columns={["名称","密钥","额度限制","已使用","状态","最后调用"]} rows={rows}/></section></>}

function Assets({notify}:{notify:(message:string)=>void}){return <section className="data-section"><header><span><h2>资产管理</h2><p>统一管理上传和生成的图片、视频、音频与文档</p></span><button onClick={()=>notify("请选择要上传的文件")}><Upload/>上传素材</button></header><div className="asset-manager-toolbar"><label><Search/><input placeholder="搜索资产"/></label><button className="active">全部</button><button>图片</button><button>视频</button><button>文档</button></div><div className="account-asset-grid">{["品牌产品主图","发布会片头","宣传方案","人物参考照","品牌视觉规范","背景音乐"].map((name,index)=><article key={name}><div className={`asset-preview p${index}`}><span>{index===1?"VIDEO":index===2||index===4?"DOC":"IMAGE"}</span></div><span><b>{name}</b><small>{index%2?"昨天":"今天"} · {(2.4+index*1.8).toFixed(1)} MB</small></span><button><Trash2/></button></article>)}</div></section>}

function Team({notify}:{notify:(message:string)=>void}){return <DataSection title="团队成员" description="邀请成员并分配角色、模型权限与月度额度" action={<button onClick={()=>notify("邀请链接已生成")}><Plus/>邀请成员</button>} columns={["成员","账号","角色","月度额度","已使用","状态","最近登录"]} rows={[["演示用户","owner@example.com","所有者","不限","¥286.40","正常","刚刚"],["林晓","lin@example.com","管理员","¥1,000","¥368.20","正常","10 分钟前"],["王薇","wei@example.com","成员","¥500","¥126.80","正常","2 小时前"],["待加入成员","new@example.com","成员","¥300","¥0.00","等待接受","—"]]}/>}
function Invite({notify}:{notify:(message:string)=>void}){return <><div className="invite-hero"><Gift/><span><small>累计邀请奖励</small><b>¥268.00</b><p>邀请好友注册并消费，你将获得长期返佣奖励。</p></span><button onClick={()=>notify("邀请链接已复制")}><Copy/>复制邀请链接</button></div><div className="account-stat-grid three"><article><span>邀请人数</span><b>18</b><small>本月新增 4 人</small></article><article><span>有效用户</span><b>12</b><small>已产生消费</small></article><article><span>待结算佣金</span><b>¥36.80</b><small>次月自动结算</small></article></div><DataSection title="邀请记录" description="查看好友注册、消费和佣金状态" columns={["用户","注册时间","累计消费","返佣比例","累计佣金","状态"]} rows={[["用户 9281","2026-09-28","¥128.00","8%","¥10.24","有效"],["用户 8270","2026-09-20","¥500.00","8%","¥40.00","有效"],["用户 6208","2026-08-14","¥1,268.00","10%","¥126.80","有效"]]}/></>}
function Tickets({notify}:{notify:(message:string)=>void}){return <DataSection title="我的工单" description="技术接入、账单与业务问题由客服持续跟进" action={<button onClick={()=>notify("新建工单窗口已打开")}><Plus/>提交工单</button>} columns={["工单号","主题","类型","优先级","状态","更新时间"]} rows={[["TK-260930-18","视频任务回调配置","技术支持","高","处理中","10 分钟前"],["TK-260928-09","企业充值发票","财务问题","普通","待回复","昨天"],["TK-260920-03","模型额度限制","账号问题","普通","已解决","09-21"]]}/>}
function AccountSettings({notify}:{notify:(message:string)=>void}){return <div className="settings-page"><section><h2>基本资料</h2><label><span>头像</span><i>灵</i><button>更换头像</button></label><label><span>昵称</span><input defaultValue="演示用户"/></label><label><span>邮箱</span><input defaultValue="user@example.com"/></label><label><span>手机号码</span><input defaultValue="138****8899"/></label><button onClick={()=>notify("基本资料已保存")}>保存资料</button></section><section><h2>安全设置</h2><label><span>登录密码<small>建议定期更新密码</small></span><button>修改</button></label><label><span>双重验证<small>登录时增加额外验证</small></span><button className="switch on"><i/></button></label><label><span>登录通知<small>异地登录发送提醒</small></span><button className="switch on"><i/></button></label><label><span>登录设备<small>当前 3 台设备</small></span><button>管理</button></label></section></div>}

function DataSection({title,description,columns,rows,action}:{title:string;description:string;columns:string[];rows:string[][];action?:ReactNode}){return <section className="data-section"><header><span><h2>{title}</h2><p>{description}</p></span>{action||<div className="table-search"><Search/><input placeholder="搜索记录"/><button>筛选 <ChevronDown/></button></div>}</header><AccountTable columns={columns} rows={rows}/></section>}
function AccountTable({columns,rows}:{columns:string[];rows:string[][]}){return <div className="account-table"><div className="head" style={{gridTemplateColumns:`repeat(${columns.length},minmax(120px,1fr))`}}>{columns.map(column=><span key={column}>{column}</span>)}</div>{rows.map((row,index)=><div key={index} style={{gridTemplateColumns:`repeat(${columns.length},minmax(120px,1fr))`}}>{row.map((cell,cellIndex)=><span key={cellIndex} className={/(正常|已完成|有效|已解决)/.test(cell)?"success":/(处理中|待回复|等待)/.test(cell)?"pending":""}>{cell}</span>)}</div>)}</div>}
